# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Edgar Kenji
tagline:          'Coding, gaming and other nerd stuff'
description:      'Coding, gaming and other nerd stuff'
url:              http://edgarkenji.github.io

author:
  name:           'Edgar Kenji'
  url:            https://twitter.com/edgarkenji

paginate:         5

# Custom vars
version:          2.0.0

github:			  https://github.com/edgarkenji

# Tags
collections:
  tags:
    output: true
    permalink: tags/:path/