# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ikusagami
tagline:          'Coding, gaming and stuff'
description:      'Mostly iOS programming with Swift and occasional ramblings about nerd stuff'
url:              http://ikusagami.com

author:
  name:           'Edgar Kenji'
  url:            https://twitter.com/edgarkenji

paginate:         5

# Custom vars
version:          2.0.0

github:			  https://github.com/edgarkenji